# Generated by Django 4.2.7 on 2023-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.CharField(default='', max_length=5),
        ),
    ]
