# Generated by Django 4.2.7 on 2023-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_event_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.CharField(max_length=5),
        ),
    ]
