# Generated by Django 4.2.7 on 2023-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
