# Generated by Django 4.2.7 on 2023-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_alter_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_socials',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
